### ISSUE TITLE
docker: Is it possible to not need privileges

### ISSUE THREAD

**Issue by zcadqewxs** [remote-android/vendor_redroid#2]
Is it possible to not need privileges
Now running requires privileges, is it possible not to require privileges

**Comment by zhouziyang** [comment]
we are emulating the entire user-space Android OS in container environment, thus many capabilities / devices are required (maybe add all these capabilities / devices manually, but effective as `--privileged` options). As I known, many k8s platforms (like EKS / AKS) are allow `--privileged` containers.
